name: image publish

on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.TOKEN }}
    
    - run: |
        docker build -t ghcr.io/gabrielnatangw/image-docker:latest -f Dockerfile .
        docker tag ghcr.io/gabrielnatangw/image-docker:latest ghcr.io/gabrielnatangw/image-docker:${{ github.sha }}
    
    - run: |
        docker push ghcr.io/gabrielnatangw/image-docker:latest
        docker push ghcr.io/gabrielnatangw/image-docker:${{ github.sha }}